name: Run benchmarks

on:
  workflow_dispatch

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        name: Set up JDK 19
        with:
          distribution: 'temurin'
          java-version: 19
      - uses: egor-tensin/setup-gcc@v1
        name: Set up GCC
        with:
          version: latest
      - uses: actions/setup-python@v4
        name: Set up latest Python
        with:
          python-version: '3.x'
      - uses: actions/setup-go@v3
        name: Set up Go 1.19.3
        with:
          go-version: '1.19.3'
          check-latest: true
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
      - name: Run benchmarks
        run: |
          python3 perf_benchmark.py --end 8
  benchmark-rust:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        name: Set up latest Python
        with:
          python-version: '3.x'
      - name: Set up latest stable Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
      - name: Run benchmarks
        run: |
          python3 perf_benchmark.py --start 8 --end 11
  benchmark-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        name: Set up latest Python
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
      - name: Run benchmarks
        run: |
          python3 perf_benchmark.py --start 11
