name: Run benchmarks

on:
  workflow_dispatch

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        name: Set up JDK 18
        with:
          distribution: 'temurin'
          java-version: 18
      - uses: egor-tensin/setup-gcc@v1
        name: Set up GCC
        with:
          version: latest
      - uses: actions/setup-python@v4
        name: Set up latest Python
        with:
          python-version: '3.x'
      - uses: actions/setup-go@v3
        name: Set up Go 1.18.4
        with:
          go-version: '1.18.4'
          check-latest: true
      - name: Set up latest stable Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
      - name: Run benchmarks (part 1)
        run: |
          python3 perf_benchmark.py --end 4
      - name: Run benchmarks (part 2)
        run: |
          python3 perf_benchmark.py --start 4 --end 8
      - name: Run benchmarks (part 3)
        run: |
          python3 perf_benchmark.py --start 8
